config/routes.rb
Abeira::Application.routes.draw do

  resources :users
  resources :sessions
  resources :agendas
  resources :podcasts

  root :to => 'home#index'

  match '/signout', to: 'sessions#destroy', via: :delete
  match '/admin',   to: 'pages#admin'
  match '/fotos',   to: 'pages#fotos'
  match '/contato',   to: 'pages#contato'
  match '/oquee',   to: 'pages#oquee'
  match '/agenda',   to: 'agendas#index'
  match '/equipe',   to: 'pages#equipe'
  match '/enviar_email',    to: 'pages#enviar_email'

end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  before_save :create_remember_token

  before_save { |user| user.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Oi! Usuario criado com sucesso"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Perfil atualizado"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Usuario excluido"
    redirect_to users_path
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!-- TÍTULO -->
<div class="row">
  <div class="large-12 columns main-content-top">
    <h2>Editar Usuário</h2>
  </div>
</div>
<% if signed_in? %>

<!-- FIM TÍTULO -->

<div class="row">
  <div class="large-12 columns">
    <%= form_for(@current_user) do |f| %>

    <!-- error form messages -->
    <% if @user.errors.any? %>
    <div id="error explanation">
      <div class="alert alert-error">
        O formulario contem <%= pluralize(@user.errors.count, "erro") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <br><br>
    <%= f.label :nome %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :senha %>
    <%= f.password_field :password %>

    <%= f.label :confirme_a_senha, "Confirme a senha" %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit"Salvar", :class => 'button large' %>

    <% end %>
  </div>
</div>

<% end %>

app/views/users/index.html.erb
<% if signed_in? %>

<!-- TÍTULO -->
<div class="row">
  <div class="large-12 columns main-content-top">
    <h2>Usuários</h2>
  </div>
</div>

<div class="content_wrapper">
  <div class="row">
    <div class="large-12 columns">
      <h4><%= link_to 'Adicionar Usuário', new_user_path %></h4>
      <h4><%= link_to 'Editar Meu Perfil', edit_user_path(current_user) %></h4><br><br>
      <h2>Lista de Usuários</h2>
      <% @users.each do |user| %>
      <h4><%= user.name %></h4>
      <% end %>
      <br>
      <br>
    </div>
  </div>
</div>

<% end %>

app/views/users/new.html.erb
<% if signed_in? %>

<!-- TÍTULO -->
<div class="row">
  <div class="large-12 columns main-content-top">
    <h2>Adicionar Usuário</h2>
  </div>
</div>
<!-- FIM TÍTULO -->

<div class="row">
  <div class="large-12 columns">
    <%= form_for(@user) do |f| %>

    <!-- error form messages -->
    <% if @user.errors.any? %>
    <div id="error explanation">
      <div class="alert alert-error">
        O formulario contem <%= pluralize(@user.errors.count, "erro") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <br><br>
    <%= f.label :nome %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :senha %>
    <%= f.password_field :password %>

    <%= f.label :confirme_a_senha, "Confirme a senha" %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit"Salvar", :class => 'button large' %>

    <% end %>
  </div>
</div>

<% end %>

app/views/users/show.html.erb
<% if signed_in? %>

<!-- TÍTULO -->
<div class="row">
  <div class="large-12 columns main-content-top">
    <h2>Usuário</h2>
  </div>
</div>
<!-- FIM TÍTULO -->
<br>
<div class="row">
  <div class="large-12 columns">
    <p id="notice"><%= notice %></p>
    <h1><%= @user.name %></h1>
    <h3><%= @user.email %></h3>
    <br><br>
    <%= link_to 'Voltar', users_path %><br><br>
  </div>
</div>

<% end %>