config/routes.rb
Abeira::Application.routes.draw do

  resources :users
  resources :sessions
  resources :agendas
  resources :podcasts

  root :to => 'home#index'

  match '/signout', to: 'sessions#destroy', via: :delete
  match '/admin',   to: 'pages#admin'
  match '/fotos',   to: 'pages#fotos'
  match '/contato',   to: 'pages#contato'
  match '/oquee',   to: 'pages#oquee'
  match '/agenda',   to: 'agendas#index'
  match '/equipe',   to: 'pages#equipe'
  match '/enviar_email',    to: 'pages#enviar_email'

end

app/models/agenda.rb
class Agenda < ActiveRecord::Base
  attr_accessible :data, :image, :texto, :titulo
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  respond_to :html

  def index
    @agendas = Agenda.all
    @agendas_by_date = @agendas.group_by(&:data)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  # GET /agendas/1
  # GET /agendas/1.json
  def show
    @agenda = Agenda.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @agenda }
    end
  end

  # GET /agendas/new
  # GET /agendas/new.json
  def new
    @agenda = Agenda.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @agenda }
    end
  end

  # GET /agendas/1/edit
  def edit
    @agenda = Agenda.find(params[:id])
  end

  # POST /agendas
  # POST /agendas.json
  def create
    @agenda = Agenda.new(params[:agenda])

    respond_to do |format|
      if @agenda.save
        format.html { redirect_to @agenda, notice: 'Agenda was successfully created.' }
        format.json { render json: @agenda, status: :created, location: @agenda }
      else
        format.html { render action: "new" }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /agendas/1
  # PUT /agendas/1.json
  def update
    @agenda = Agenda.find(params[:id])

    respond_to do |format|
      if @agenda.update_attributes(params[:agenda])
        format.html { redirect_to @agenda, notice: 'Agenda was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agendas/1
  # DELETE /agendas/1.json
  def destroy
    @agenda = Agenda.find(params[:id])
    @agenda.destroy

    respond_to do |format|
      format.html { redirect_to agendas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/views/agendas/_form.html.erb
<br><br>
<%= form_for(@agenda) do |f| %>
  <% if @agenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agenda.errors.count, "error") %> prohibited this agenda from being saved:</h2>

      <ul>
      <% @agenda.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :texto %><br />
    <%= f.text_area :texto, :class => 'ckeditor' %>
  </div><br>
<!--   <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div> -->

  <div class="field">
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </div><br>
  <div class="actions">
    <%= f.submit"Salvar", :class => 'button large' %>
  </div>
<% end %>

app/views/agendas/edit.html.erb
<% if signed_in? %>

<!-- TÍTULO -->
<div class="row">
  <div class="large-12 columns main-content-top">
    <h2>Editar Ítem Da Agenda</h2>
  </div>
</div>
<!-- FIM TÍTULO -->

<div class="row">
  <div class="large-12 columns">
    <%= render 'form' %>
  </div>
</div>

<% end %>

app/views/agendas/index.html.erb
<!-- TÍTULO -->
<div class="row">
  <div class="large-12 columns main-content-top">
    <h2>Agenda</h2>
  </div>
</div>
<!-- FIM TÍTULO -->


<!-- admin only -->
<% if signed_in? %>
<div class="content_wrapper">
  <div class="row">
    <div class="large-12 columns">
      <h4><%= link_to 'Adicionar Ítem Na Agenda', new_agenda_path %></h4>
    </div>     
  </div>
</div> 
<% end %>
<!-- admin only -->

<br>
<div class="row">
  <div class="large-12 columns"><br>
    <div id="articles">
      <h1 id="month">
        <%= link_to "<", date: @date.prev_month %>
        <%= @date.strftime("%m / %Y") %>
        <%= link_to ">", date: @date.next_month %>
      </h1>
      <%= calendar do |date| %>
      <%= date.day %>
      <% if @agendas_by_date[date] %>
      <ul>
        <% @agendas_by_date[date].each do |agenda| %>
        <li><h4 class="button success"><%= link_to agenda.titulo, agenda %></h4></li>
        <% end %>
      </ul>
      <% end %>
      <% end %>
    </div>
  </div>
</div>
<br>
<br>
<br>

app/views/agendas/new.html.erb
<% if signed_in? %>

<!-- TÍTULO -->
<div class="row">
  <div class="large-12 columns main-content-top">
    <h2>Adicionar Ítem Na Agenda</h2>
  </div>
</div>
<!-- FIM TÍTULO -->

<div class="row">
  <div class="large-12 columns">
    <%= render 'form' %>
  </div>
</div>

<% end %>

app/views/agendas/show.html.erb
<!-- TÍTULO -->
<div class="row">
  <div class="large-12 columns main-content-top">
    <h2>Agenda</h2>
  </div>
</div>
<!-- FIM TÍTULO -->
<br>
<div class="row">
  <div class="large-12 columns">
    <p id="notice"><%= notice %></p>
    <h1><%= @agenda.titulo %></h1>
    <h3><%= @agenda.data.strftime("%d/%m/%Y") %></h3>
    <p><%= raw(@agenda.texto) %><br></p>

    
    <%= link_to 'Voltar', agendas_path %> 
    <!-- admin only -->
    <% if signed_in? %>
    |
    <%= link_to 'Editar', edit_agenda_path(@agenda) %> |
    <%= link_to 'Deletar', @agenda, method: :delete, data: { confirm: 'Tem certeza?' } %>
    <!-- admin only -->
    <% end %>
    <br><br><br>
  </div>
</div>