config/routes.rb
Abeira::Application.routes.draw do

  resources :users
  resources :sessions
  resources :agendas
  resources :podcasts

  root :to => 'home#index'

  match '/signout', to: 'sessions#destroy', via: :delete
  match '/admin',   to: 'pages#admin'
  match '/fotos',   to: 'pages#fotos'
  match '/contato',   to: 'pages#contato'
  match '/oquee',   to: 'pages#oquee'
  match '/agenda',   to: 'agendas#index'
  match '/equipe',   to: 'pages#equipe'
  match '/enviar_email',    to: 'pages#enviar_email'

end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  attr_accessible :image, :soundcloud, :texto, :titulo
  mount_uploader :image, ImageUploader
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  respond_to :html

  def index
    @podcasts = Podcast.order("id DESC").paginate(:page => params[:page], :per_page => 5)
  end

  def show
    @podcast = Podcast.find(params[:id])
  end

  def new
    @podcast = Podcast.new
  end

  # GET /podcasts/1/edit
  def edit
    @podcast = Podcast.find(params[:id])
  end

  # POST /podcasts
  # POST /podcasts.json
  def create
    @podcast = Podcast.new(params[:podcast])

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to @podcast, notice: 'Podcast criado com sucesso!' }
        format.json { render json: @podcast, status: :created, location: @podcast }
      else
        format.html { render action: "new" }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /podcasts/1
  # PUT /podcasts/1.json
  def update
    @podcast = Podcast.find(params[:id])

    respond_to do |format|
      if @podcast.update_attributes(params[:podcast])
        format.html { redirect_to @podcast, notice: 'Podcast was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1
  # DELETE /podcasts/1.json
  def destroy
    @podcast = Podcast.find(params[:id])
    @podcast.destroy

    respond_to do |format|
      format.html { redirect_to podcasts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/podcasts/_form.html.erb
<br><br>
<%= form_for @podcast, :html => {:multipart => true} do |f| %>
  <% if @podcast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@podcast.errors.count, "error") %> prohibited this podcast from being saved:</h2>

      <ul>
      <% @podcast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :título %><br />
    <%= f.text_field :titulo %>
  </div>
    <div class="field">
    <%= f.label :imagem %><br />
    <%= f.file_field :image %><br /><br />
  </div>
  <div class="field">
    <%= f.label :texto %><br />
    <%= f.text_area :texto, :class => 'ckeditor' %>
  </div><br>
  <div class="field">
    <%= f.label :soundcloud %><br />
    <%= f.text_field :soundcloud %>
  </div><br>
  <div class="actions">
    <%= f.submit"Salvar", :class => 'button large' %>
  </div>
<% end %>
<br><br>

app/views/podcasts/edit.html.erb
<% if signed_in? %>

<!-- TÍTULO -->
<div class="row">
  <div class="large-12 columns main-content-top">
    <h2>Editar Podcast</h2>
  </div>
</div>
<!-- FIM TÍTULO -->

<div class="row">
  <div class="large-12 columns">
    <%= render 'form' %>
  </div>
</div>

<% end %>

app/views/podcasts/index.html.erb
<!-- TÍTULO -->
<div class="row">
  <div class="large-12 columns main-content-top">
    <h2>Podcast</h2>
  </div>
</div>
<!-- FIM TÍTULO -->
<br>


<!-- admin only -->
<% if signed_in? %>
<div class="content_wrapper">
  <div class="row">
    <div class="large-12 columns">
      <h4><%= link_to 'Adicionar Podcast', new_podcast_path %></h4>
    </div>     
  </div>
</div> 
<% end %>
<!-- admin only -->

<% @podcasts.each do |podcast| %>

<div class="content_wrapper">
  <div class="row">
    <div class="large-12 columns">
      <article class="post col-1">
        <iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%<%= podcast.soundcloud %>"></iframe>
        <h2><%= podcast.titulo %></h2>
        <p>Postado em <em><%= podcast.created_at.strftime("%d/%m/%Y") %></em></p>
        <p class="post_text"><%= raw(HTML_Truncator.truncate(podcast.texto, 75)) %></p>
        <%= link_to 'Leia mais', podcast, :class => "button" %>

        <!-- admin only -->
        <% if signed_in? %>
        &nbsp <%= link_to 'Editar', edit_podcast_path(podcast) %> | <%= link_to 'Deletar', podcast, method: :delete, data: { confirm: 'Tem certeza?' } %>
        <% end %>
        <!-- admin only -->

      </article>
    </div>     
  </div>
</div>           

<% end %>

<div class="pagination-wrapper">
  <div class="row">
    <div class="large-12 columns">
      <h3><%= will_paginate @podcasts, previous_label: h("<<"), next_label: h(">>") %></h3>
      <div class="clearfix"></div>
    </div>
  </div>
</div>

app/views/podcasts/new.html.erb
<% if signed_in? %>

<!-- TÍTULO -->
<div class="row">
  <div class="large-12 columns main-content-top">
    <h2>Adicionar Podcast</h2>
  </div>
</div>
<!-- FIM TÍTULO -->

<div class="row">
  <div class="large-12 columns">
    <%= render 'form' %>
  </div>
</div>

<% end %>

app/views/podcasts/show.html.erb
<!-- TÍTULO -->
<div class="row">
  <div class="large-12 columns main-content-top">
    <h2>Podcast</h2>
  </div>
</div>
<!-- FIM TÍTULO -->
<br>
<div class="row">
  <div class="large-12 columns">
    <p id="notice"><%= notice %></p>
    <h1><%= @podcast.titulo %></h1>
    <p>Postado em <em><%= @podcast.created_at.strftime("%d/%m/%Y") %></em></p>
    <iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%<%= @podcast.soundcloud %>"></iframe><br><br>    
    <!-- <%= image_tag @podcast.image_url if @podcast.image? %> -->    
    <%= raw(@podcast.texto) %><br><br>
    <%= link_to 'Voltar', podcasts_path %><br><br>
  </div>
</div>