config/routes.rb
Abeira::Application.routes.draw do

  resources :users
  resources :sessions
  resources :agendas
  resources :podcasts

  root :to => 'home#index'

  match '/signout', to: 'sessions#destroy', via: :delete
  match '/admin',   to: 'pages#admin'
  match '/fotos',   to: 'pages#fotos'
  match '/contato',   to: 'pages#contato'
  match '/oquee',   to: 'pages#oquee'
  match '/agenda',   to: 'agendas#index'
  match '/equipe',   to: 'pages#equipe'
  match '/enviar_email',    to: 'pages#enviar_email'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]>  <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="pt-br"> <!--<![endif]-->

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>À Beira | Um podcast sem eira nem beira.</title>
  <meta name="description" content="Confira aqui uma turminha do barulho aprontando altas aventuras em um Podcast À Beira da loucura." /> 

  <link rel="shortcut icon" href="/favicon.ico">

  <!-- Smallipop CSS - Tooltips -->
  <link rel="stylesheet" href="../../plugins/smallipop/css/contrib/animate.min.css" type="text/css" media="all" title="Screen" />
  <link rel="stylesheet" href="../../plugins/smallipop/css/jquery.smallipop.css" type="text/css" media="all" title="Screen" />

  <!-- Default CSS -->
  <link rel="stylesheet" href="../../css/normalize.css" />
  <link rel="stylesheet" href="../../css/foundation.css" />
  <link rel="stylesheet" href="../../css/fgx-foundation.css" />
  <!--[if IE 8]>
    <link rel="stylesheet" href="../../css/ie8-grid-foundation-4.css" />
    <![endif]-->

    <!-- Font Awesome - Retina Icons -->
    <link rel="stylesheet" href="../../plugins/fontawesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="../../css/nivo-slider.css" />
    <link rel="stylesheet" href="../../css/themes/default/default.css" />
    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="../../css/style.css" />

    <!-- Included JS Files -->
    <script src="../../js/vendor/jquery.js"></script>
    <script src="../../js/vendor/custom.modernizr.js"></script>

    <!-- carouFredSel plugin -->
    <script src="../../plugins/carouFredSel/jquery.carouFredSel-6.2.0-packed.js"></script>
    <script src="../../plugins/carouFredSel/helper-plugins/jquery.touchSwipe.min.js"></script>

    <!-- Twitter -->
    <script type="text/javascript" src="../../plugins/twitter/jquery.jtweetsanywhere-1.3.1.min.js"></script>

    <!-- Scripts Initialize -->

    <script type="text/javascript" src="../../js/jquery.nivo.slider.pack.js"></script>
    <script type="text/javascript" src="../../js/app-head-calls.js"></script>
    <script type="text/javascript">

  // Carousel
  $(window).load(function() {
    $('#slider').nivoSlider();    
    $("#carousel-type1").carouFredSel({
      responsive: true,
      width: '100%',
      auto: false,
      circular : false,
      infinite : false, 
      items: {visible: {min: 1,max: 4},
    },
    scroll: {
      items: 1,
      pauseOnHover: true
    },
    prev: {
      button: "#prev2",
      key: "left"
    },
    next: {
      button: "#next2",
      key: "right"
    },
    swipe: true
  });

    $(".work_slide ul").carouFredSel({
      circular: false,
      infinite: true,
      auto: false,
      scroll:{items:1},
      prev: { button: "#slide_prev", key: "left"},
      next: { button: "#slide_next",key: "right"}
    });
    $("#testimonial_slide").carouFredSel({
      circular: false,
      infinite: true,
      auto: false,
      scroll:{items:1},
      prev: { button: "#slide_prev1", key: "left"},
      next: { button: "#slide_next1",key: "right"}
    });
  });  

  </script>

  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>

<body>

  <div class="top-header">
    <div class="main-wrapper">
      <div class="row">
        <div class="large-7 columns">
          <ul class="inline-list">
            <li><a href="/">Home</a></li>
            <li><a href="/podcasts">Podcast</a></li>
            <li><a href="/agenda">Agenda</a></li>
            <li><a href="/fotos">Fotos</a></li>
            <li><a href="#">Colunas</a></li>
            <li><a href="/equipe">Equipe</a></li> 
            <li><a href="/contato">Contato</a></li>           
          </ul>
        </div>
        <div class="small-5 columns  text-right">
          <span>contato@abeira.com</span>
          <% if signed_in? %>
            <a href="/admin" class="button login"><i class="icon-lock"></i>Admin</a>
            <%= link_to "Sign out", signout_path, method: "delete", :class => "button login" %>
          <% else %>
            <a href="/sessions/new" class="button login"><i class="icon-lock"></i>Login</a>
          <% end %>
        </div> 
      </div>
    </div>
  </div>
  <!-- Begin Main Wrapper -->
  <div class="main-wrapper">
    <!-- Main Navigation -->  
    <header class="row main-navigation">
      <div class="large-3 columns"> 
        <a href="/" id="logo"><img src="../../images/logo.png" alt="A Beira Logo" /></a>
      </div>
      <div class="large-9 columns">     
        <nav class="top-bar">
          <ul class="title-area">
            <!-- Title Area -->
            <li class="name"></li>
            <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
            <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
          </ul>

          <section class="top-bar-section">
            <!-- Left Nav Section -->
            <ul class="right">
              <li><a class="<%= current_page('home','index') %>" href="/">Home</a></li>
              <li><a class="<%= current_page('podcasts','index') %>" href="/podcasts">Podcast</a></li>
              <li><a class="<%= current_page('agendas','index') %>" href="/agenda">Agenda</a></li>
              <li><a class="<%= current_page('pages','fotos') %>" href="/fotos">Fotos</a></li>
              <!-- <li><a href="#">Vídeos</a></li> -->
              <li><a href="">Colunas</a></li>
              <li><a class="<%= current_page('pages','equipe') %>" href="/equipe">Equipe</a></li>
              <li><a class="<%= current_page('pages','contato') %>" href="/contato">Contato</a></li>
            </ul>
            <!-- End Left Nav Section -->          
          </section>
        </nav>
      </div>
    </header>

    <%= yield %>

  </div>
  <div class="footer_wrapper">
    <footer class="row footer-part">
      <div class="large-12 columns">
        <div class="row">

          <div class="large-3 columns">
            <h4 class="footer-title">Facebook</h4>
            <div class="footer_part_content">
            <iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fabeirapodcast&amp;width=235&amp;height=258&amp;show_faces=true&amp;colorscheme=dark&amp;stream=false&amp;show_border=false&amp;header=false&amp;appId=233477100111724" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:235px; height:258px;" allowTransparency="true"></iframe>
              <div class="row collapse">
              </div>
            </div>
          </div>

          <div class="large-3 columns">
            <h4 class="footer-title">Twitter</h4>
            <div id="tweetFeed"> </div> 
            <a class="twitter-timeline" width="240" height="219" href="https://twitter.com/abeirapodcast" data-widget-id="357384577683169280"></a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>


          </div>

          <div class="large-3 columns">
            <h4 class="footer-title">Sobre</h4>
            <div class="footer_part_content">
              <p><b>Podcasts e videocasts</b> sobre tudo que você imaginar, só escolher um e escutar com todo prazer!</p>
              <ul class="about-info">
                <li><i class="icon-home"></i><span>Rio Grande do Sul</span></li>
                <li><i class="icon-phone"></i><span>(51) 9101.7921</span></li>
                <li><i class="icon-envelope"></i><a href="mailto:contato@abeira.com">contato@abeira.com</a></li>
              </ul>
            </div>
          </div>
          
          <div class="large-3 columns"> 
            <h4 class="footer-title">Contato</h4>
            <form method="POST" action="enviar_email.html" id="footer-contact-form">
              <div class="footer_part_content">
                <div class="row">
                  <div class="small-6 columns">
                    <input type="text" placeholder="Nome"  name="nome" />
                  </div>
                  <div class="small-6 columns">
                    <input type="text" placeholder="E-mail" name="email" />
                  </div>
                  <div class="small-12 columns">
                    <input type="text" placeholder="Website" name="website" />
                  </div>
                  <div class="small-12 columns">
                    <textarea cols="10" rows="15"  name="mensagem" placeholder="Mensagem"></textarea>
                  </div>
                  <div class="small-4 columns">
                    <input type="submit" class="button right" value="Enviar" name="send" />
                  </div>

                </div>
              </div>
            </form>
          </div> 
        </div>
      </div>
    </footer>

    <div class="privacy footer-part">
     <a href="#" class="scrollup">Scroll</a>
     <div class="row footer_bottom">
      <div class="large-6 columns">
        <p>&copy; 2013 abeira.com</p>
      </div>
      <div class="large-2 columns right">
        <div class="row collapse">
          <ul class="social-icons">
            <li><a target="_blank" href="https://twitter.com/abeirapodcast"><i class="icon-twitter"></i></a></li>
            <li><a target="_blank" href="https://www.facebook.com/ABeiraPodcast"><i class="icon-facebook"></i></a></li>
            <li><a target="_blank" href="https://plus.google.com/117773317991969499089"><i class="icon-google-plus"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
document.write('<script src=' +
  ('__proto__' in {} ? 'js/vendor/zepto' : 'js/vendor/jquery') +
  '.js><\/script>')
</script> 

<script src="js/foundation.min.js"></script>

<script>
$(document).foundation();
</script>  

<!-- Smallipop JS - Tooltips -->
<script type="text/javascript" src="../../plugins/smallipop/lib/contrib/prettify.js"></script>
<script type="text/javascript" src="../../plugins/smallipop/lib/jquery.smallipop.js"></script>
<script type="text/javascript" src="../../plugins/smallipop/lib/smallipop.calls.js"></script> 

<!-- Initialize JS Plugins -->
<script src="../../js/app-bottom-calls.js"></script>  

<!-- End Main Wrapper -->

</body>

</html>